#!/bin/sh
sudo apt-get -y install vim tmux git bzr mercurial
wget -O ~/.tmux.conf https://raw.github.com/mattyw/dotfiles/master/tmux.conf
wget -O ~/.vimrc https://raw.github.com/mattyw/dotfiles/master/vimrc
cat "set editing-mode vi" > ~/.inputrc
